# Generated by Django 5.2.12 on 2026-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
